version: "3"
services:
  web-content:
    build:
      dockerfile: Dockerfile-dev
      context: .
    image: alexsimons/web-content:0.1.0
    volumes:
      - "./:/app"
    ports:
      - "9696:3000"