version: "3"
services:
  web-content:
    build:
      dockerfile: Dockerfile-install
      context: .
    image: alexsimons/nodeinstall:9.2.0
    volumes:
      - "./:/app"
    entrypoint:
      - /bin/bash
    command:
      - "-c"
      - "cd web-content; npm run watch"
    ports:
      - "3000:3000"